### ISSUE TITLE
[@expo/vector-icons] Error: Downloaded file for asset

### ISSUE THREAD

**Issue by Enricopv** [JacopoPatroclo/nx-react-native-expo#3]
Pretty awesome tool so far!

When I run ```nx start {app}``` I eventually get this warning when trying to use FontAwesome5 (or any font) from @expo/vector-icons.

`[Unhandled promise rejection: Error: Downloaded file for asset 'FontAwesome5_Solid.ttf' Located at http://192.168.1.6:19000/assets/../../node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome5_Solid.ttf?platform=android&hash=1ab236ed440ee51810c56bd16628aef0?platform=android&dev=true&hot=false&minify=false failed MD5 integrity check]`

This also results in the Icon not appearing.

If I were to guess, I dont think the file path is quite right. I think it needs to go up one more level.
```
// Currently this
http://192.168.1.6:19000/assets/../../node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome5_Solid.ttf

// Should be this with one more move up the directory from assets?
http://192.168.1.6:19000/assets/../../../node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome5_Solid.ttf
```

Thanks for this!

**Comment by JacopoPatroclo** [comment]
Hi, I'm not sure how to fix this issue on my end but I'll look into it this weekend. If @Enricopv or someone else have other suggestions on this topic feel free to contribute :)

**Comment by iquabius** [comment]
This happens because the Metro bundler has an issue loading assets outside the app's directory, and `@expo/vector-icons` is located in the root `node_modules` directory.

> this issue is related to the use of monorepo. It will happen with any filename. The reproducible demo here uses monorepo and any filename will fail with the same error. - https://github.com/expo/expo/issues/5566#issuecomment-585805621

There are some solutions in the linked issue, like copying the font file to the app's `assets` directory and manually loading it. It's not ideal, but I tested it, and it worked.

I think a better solution is to add `@expo/vector-icons` to the `"dependencies"` list in the app's `package.json` file. That would signal to the Nx plugin that it should create a symlink for the dependency in the app's `node_module` directory.

But the implementation of [ensure-node-modules-symlink.ts](https://github.com/JacopoPatroclo/nx-react-native-expo/blob/master/packages/react-native-expo/src/utils/ensure-node-modules-symlink.ts) doesn't handle scoped packages yet. The official [@nrwl/react-native](https://github.com/nrwl/nx-react-native/blob/main/packages/react-native/src/utils/ensure-node-modules-symlink.ts) plugin seems to handle scoped packages.

IMO this would be the cleanest way to tackle this problem.

I dug into this issue some time ago, and now I can't reproduce it anymore on my local repository. There must be something caching it from when I tried loading the font manually.

**Comment by JacopoPatroclo** [comment]
Thanks @iquabius for the heads up. I'll implement this features using the @nrwl/react-native package as a reference.

Task https://github.com/JacopoPatroclo/nx-react-native-expo/projects/1#card-52323015

**Comment by JacopoPatroclo** [comment]
I've tested and I've been able to reproduce the issue only on android. I suspect thate it depends how android handle custom fonts. Furthermore I've found that all the fonts must be copyed inside `android/app/src/main/assets/fonts` to be imported correctly, instead for iOS the only thing that change is a reference inside the project.pbxproj file, the fonts are imported during build time and they can be anywhere in the project (the referece of where they are is inside project.pbxproj). Having said that I've pushed the support for scoped package inside [this pull request](https://github.com/JacopoPatroclo/nx-react-native-expo/pull/7). @Enricopv if you want you can gave me feedback and try it out localy in your not-working project. I've already tested but until there are no automatic tests, two it's better than one ;) Thanks in advanced and sorry for the delay. Let me know

**Comment by JacopoPatroclo** [comment]
Fix in new version 0.0.9

**Comment by Enricopv** [comment]
Thanks for taking the time to figure it out! I'll give it a try!

**Comment by seyaobey** [comment]
Hi @JacopoPatroclo . First thanks for the amazing tool! 

Just to signal I'm having the same issue with

`"nx-react-native-expo": "^0.0.9",`

`Error: Downloaded file for asset 'MaterialCommunityIcons.ttf' Located at http://192.168.1.20:19001/assets/../../../node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/MaterialCommunityIcons.ttf?platform=android&hash=6a2ddad1092a0a1c326b6d0e738e682b?platform=android&dev=true&hot=false&minify=false failed MD5 integrity check`

**Comment by JacopoPatroclo** [comment]
@seyaobey did you added the vector icon expo package to the project.json of your app. If the answer is yes try to to delete the app node_modules and re-run the project. Let me know how it goes. If you want furthers help post your package.json's app here or, if you can,your project's repo.

**Comment by seyaobey** [comment]
@JacopoPatroclo I've just created a brand new nx workspace with a simple `react-native-expo` app. I've also made sure I've got `@expo/vector-icons` accessible in my application. (I believe it is bundled with the whole `expo` library).
Here is the repository which reproduce this issues:

`git clone https://github.com/seyaobey/nx-test.git`

After having run `npm install / yarn install`, run also `npm run expo:start (yarn expo:start)` to start the metro bundler with my default app.

**Comment by JacopoPatroclo** [comment]
@seyaobey here `https://github.com/seyaobey/nx-test/blob/main/apps/test-app/package.json` you should add to the "dependencies" the @expo/vector-icons packages so it will be linked properly. Add "@expo/vector-icons": "*" after line 6. This should solve the problem. Let me know :)

**Comment by seyaobey** [comment]
@JacopoPatroclo Thanks, it is working now!
